### ISSUE TITLE
Webapp not correctly displaying file upload error message

### ISSUE THREAD

**Issue by theabramkhan** [mattermost/mattermost-plugin-antivirus#36]
i receive no error message from infected files in the user interface.
The only thing that i get is console log.
`
{"timestamp":"2022-08-01 15:34:32.047 Z","level":"warn","msg":"The antivirus service would not allow you to attach this file.","caller":"app/plugin_api.go:943","plugin_id":"antivirus","filename":"New Text Document.txt","user":"1xm4u1a6nibmtnuym4o678qdgy","scan_result":"stream: Win.Test.EICAR_HDB-1 FOUND"}
`

**Comment by shiftZZnet** [comment]
Mattermost version: 7.2.0
Plugin version: 0.1.2
ClamAV version: ClamAV 0.103.6/26650/Tue Sep  6 09:55:26 2022

I have the same issue. When trying to upload the test virus the system is reporting in `/var/log/syslog` the the file is being rejected:

```
Sep  6 13:57:45 mm7-mattermost clamd[8086]: Tue Sep  6 13:57:45 2022 -> instream(127.0.0.1@1895): Eicar-Signature(69630e4574ec6798239b091cda43dca0:69) FOUND
Sep  6 13:57:45 mm7-mattermost clamd[8086]: instream(127.0.0.1@1895): Eicar-Signature(69630e4574ec6798239b091cda43dca0:69) FOUND
Sep  6 13:57:45 mm7-mattermost mattermost[2642]: {"timestamp":"2022-09-06 13:57:45.257 +02:00","level":"warn","msg":"The antivirus service would not allow you to attach this file.","caller":"app/plugin_api.go:978","plugin_id":"antivirus","filename":"eicar_test_virus.txt","user":"6mj4ujyggbdepmrhoo5m7xrpec","scan_result":"stream: Eicar-Signature FOUND"}
```
But the only thing I see on the GUI is the "running" upload process bar like shown here:
<img width="817" alt="Screenshot 2022-09-06 at 14 59 00" src="https://user-images.githubusercontent.com/106601931/188642472-8037c382-fd53-41c9-af82-2b8a29216ae4.png">

No error messages occurs in the GUI.

Thanks for any hint!
Joachim.

**Comment by Ar1ste1a** [comment]
Same thing here as the other two, clearly the docker container is working properly but for whatever reason Mattermost does not register it as complete

**Comment by sergonas** [comment]
Reason of this bug is refactoring file file_actions.ts at https://github.com/mattermost/mattermost-webapp/pull/10169
Error message from server handles at xhr.onerror, but xhr.onerror called only on network troubles.
So no handler calls on 
Server sends correct answer, but webapp cannot proccess it. 

Server response example: 
<img width="551" alt="изображение" src="https://user-images.githubusercontent.com/1069076/196754771-03cf9d09-a65a-4e98-a866-9225e84a2bed.png">
It's another error that causes similar behaviour.

Unfortunately, my front-end expertise allows me only locate bug, not to fix it

**Comment by ewwollesen** [comment]
@mickmister FYI, but I think this can be closed as the underlying webapp issue appears to be have been fixed. We had a customer experiencing this a while back and I just confirmed with them it was resolved.
